In [22]:
import torch
import numpy as np
from torchvision import datasets, transforms

Tensor Creation

In [2]:
x=torch.tensor([1,2,3])
y=torch.tensor([4,5,5])#Vector
a=torch.tensor([[1,2,3],[5,6,2],[7,8,9]])#Matrix
b=torch.tensor([[4,5,6],[5,90,23],[34,89,67]])#Matrix
p=torch.from_numpy(np.array([1,45,67]))#Numpy array to tensor

In [3]:
print(a)
print(a.dtype)

tensor([[1, 2, 3],
        [5, 6, 2],
        [7, 8, 9]])
torch.int64


Tensor Manipulation

1.Matrix multiplication

In [4]:
c=torch.matmul(a,b)
print(c)

tensor([[ 116,  452,  253],
        [ 118,  743,  302],
        [ 374, 1556,  829]])


2.Vector addition

In [5]:
z=torch.add(x,y)
print(z)

tensor([5, 7, 8])


3.Element wise Multiplication

In [6]:
w=torch.mul(x,y)
print(w)

tensor([ 4, 10, 15])


4.Mean 

In [7]:
mean=torch.mean(x.float())
print(mean)

tensor(2.)


5.Within Tensor Sum

In [8]:
sum=torch.sum(p)
print(sum)

tensor(113)


6.Concatenation

In [9]:
m=torch.cat((x,y),dim=0)
m1=torch.sum(m)
print(m1)

tensor(20)


7.RESHAPING

In [13]:
print(a)
d=a.view(9)
print(d)


tensor([[1, 2, 3],
        [5, 6, 2],
        [7, 8, 9]])
tensor([1, 2, 3, 5, 6, 2, 7, 8, 9])


8.Element wise functions

In [14]:
a1=torch.abs(d)
print(a1)

b1=torch.sqrt(c.float())
print(b1)

tensor([1, 2, 3, 5, 6, 2, 7, 8, 9])
tensor([[10.7703, 21.2603, 15.9060],
        [10.8628, 27.2580, 17.3781],
        [19.3391, 39.4462, 28.7924]])


10.Some other functions

In [15]:
max=torch.max(a)
print(max)
argmax=torch.argmax(c)
print(argmax)

tensor(9)
tensor(7)


Automatic differentiation

In [21]:
x=torch.tensor([1.3,2.9,6.7],requires_grad=True)
y=x**3+4*x**2+5
y.sum().backward()
print(x.grad)

tensor([ 15.4700,  48.4300, 188.2700])


Data Loading

1.Accessing Dataset within Pytorch package

Loading Dataset

Here transform class converts the data from MNIST dataset into Tensors

In [28]:
traindata=datasets.MNIST(root='data',train=True,download=True,transform=transforms.ToTensor())
testdata=datasets.MNIST(root='data',train=False,download=True,transform=transforms.ToTensor())


Accessing sample and labels and also acccessing a specific example

In [29]:
train_samples=traindata.data
train_labels=traindata.targets
print(train_samples.shape)
print(train_labels.shape)
sample, label=traindata[8]
print(sample.shape)

torch.Size([60000, 28, 28])
torch.Size([60000])
torch.Size([1, 28, 28])


2.Custom dataset 

In [37]:
from torch.utils.data import Dataset
class Customdataset(Dataset):
    def __init__ (self, data, labels, transform=None):
        self.data=data
        self.labels=labels
        self.transform=transform
    def __len__(self):
        return len(self.data)
    def __getitem__(self, idx):
        sample=self.data[idx]
        label=self.labels[idx]
        if self.transform:
            sample=self.transform(sample)
            return sample, label

train_samples=''''''
train_labels=''' '''   

#Initialize the custom dataset
customdataset=Customdataset(train_samples, train_labels, transform=transforms.ToTensor())        